esphome:
  name: air_quality

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "<WI-FI_SSID>"
  password: "<WI-FI_PASSWORD>"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air Quality Fallback Hotspot"
    password: "ycgZIpImlNvV"

captive_portal:

i2c:
  sda: 18
  scl: 19
  scan: true
  id: bus_a

globals:

  - id: esphome_sensitivity
    type: float
    initial_value: '36.5'
    restore_value: yes

  - id: esphome_volume
    type: int

# provide here values for range
  - id: lux_level
    type: int[5]
    initial_value: '{0, 100, 200, 300, 400}'

  - id: sound_level
    type: int[5]
    initial_value: '{0, 20, 40, 60, 80}'

  - id: CO2_level
    type: int[5]
    initial_value: '{0, 200, 400, 600, 800}'

  - id: humidity_level
    type: int[5]
    initial_value: '{0, 20, 40, 60, 80}'

  - id: temp_level
    type: int[5]
    initial_value: '{0, 10, 15, 25, 35}'


sensor:  
  - platform: scd4x
    update_interval: 5s
    co2:
      name: "scd4x CO2"
      id: scd4x_co2
    temperature:
      name: "scd4x Temperature"
    humidity:
      name: "scd4x Humidity"

  - platform: bh1750
    name: "BH1750 Illuminance"
    id: bh1750_lux
    address: 0x23
    update_interval: 5s
    
  - platform: sht3xd
    temperature:
      name: "sht3xd Temperature"
      id: sht3xd_temp
    humidity:
      name: "sht3xd Humidity"
      id: sht3xd_hum
    update_interval: 5s
    
# Example configuration entry
  - platform: adc
    pin: 0
    id: esphome_db
    device_class: signal_strength
    name: "Db SoundEsp"
    icon: "mdi:volume-vibrate"
    unit_of_measurement: "db"
    update_interval: 2s
    raw: true
    filters:
      - lambda: |-
          unsigned int sample;
          unsigned long startMillis= millis(); 
          float peakToPeak = 0; 
          unsigned int signalMax = 0;
          unsigned int signalMin = 1024;
          while (millis() - startMillis < 500) {
            sample = analogRead(0);
            if (sample < 1024){
                if (sample > signalMax){
                    signalMax = sample;
                }
                else if (sample < signalMin){
                    signalMin = sample;
                }
              }
          }
          peakToPeak = map((signalMax - signalMin),1,1024,1.5,1024);
          id(esphome_volume) = peakToPeak;
          float state = id(esphome_sensitivity)*log10(peakToPeak)+15;  
          return(state);

  - platform: template
    name: "Illuminance quality level"
    update_interval: 5s
    lambda: !lambda |-
      unsigned int currentOutputLevel = 0 ;
      unsigned int lb = id(lux_level)[currentOutputLevel];
      unsigned int ub = id(lux_level)[currentOutputLevel + 1];
      if ( id(bh1750_lux).state < lb || id(bh1750_lux).state > ub ) {
        unsigned int i;
        for ( i = 0 ; i < 4 ; i++ ) {
          if ( id(bh1750_lux).state >= id(lux_level)[i] && id(bh1750_lux).state <= id(lux_level)[i+1] ) break ;
        }
      currentOutputLevel = i ;
      }
      return currentOutputLevel + 1;

  - platform: template
    name: "Sound quality level"
    update_interval: 5s
    lambda: !lambda |-
      unsigned int currentOutputLevel = 0 ;
      unsigned int lb = id(sound_level)[currentOutputLevel];
      unsigned int ub = id(sound_level)[currentOutputLevel + 1];
      if ( id(esphome_db).state < lb || id(esphome_db).state > ub ) {
        unsigned int i;
        for ( i = 0 ; i < 4 ; i++ ) {
          if ( id(esphome_db).state >= id(sound_level)[i] && id(esphome_db).state <= id(sound_level)[i+1] ) break ;
        }
      currentOutputLevel = i ;
      }
      return currentOutputLevel + 1 ;

  - platform: template
    name: "CO2 quality level"
    update_interval: 5s
    lambda: !lambda |-
      unsigned int currentOutputLevel = 0 ;
      unsigned int lb = id(CO2_level)[currentOutputLevel];
      unsigned int ub = id(CO2_level)[currentOutputLevel + 1];
      if ( id(scd4x_co2).state < lb || id(scd4x_co2).state > ub ) {
        unsigned int i;
        for ( i = 0 ; i < 4 ; i++ ) {
          if ( id(scd4x_co2).state >= id(CO2_level)[i] && id(scd4x_co2).state <= id(CO2_level)[i+1] ) break ;
        }
      currentOutputLevel = i ;
      }
      return currentOutputLevel + 1 ;

  - platform: template
    name: "humidity quality level"
    update_interval: 5s
    lambda: !lambda |-
      unsigned int currentOutputLevel = 0 ;
      unsigned int lb = id(humidity_level)[currentOutputLevel];
      unsigned int ub = id(humidity_level)[currentOutputLevel + 1];
      if ( id(sht3xd_hum).state < lb || id(sht3xd_hum).state > ub ) {
        unsigned int i;
        for ( i = 0 ; i < 4 ; i++ ) {
          if ( id(sht3xd_hum).state >= id(humidity_level)[i] && id(sht3xd_hum).state <= id(humidity_level)[i+1] ) break ;
        }
      currentOutputLevel = i ;
      }
      return currentOutputLevel + 1 ;

  - platform: template
    name: "temperature quality level"
    update_interval: 5s
    lambda: !lambda |-
      unsigned int currentOutputLevel = 0 ;
      unsigned int lb = id(temp_level)[currentOutputLevel];
      unsigned int ub = id(temp_level)[currentOutputLevel + 1];
      if ( id(sht3xd_temp).state < lb || id(sht3xd_temp).state > ub ) {
        unsigned int i;
        for ( i = 0 ; i < 4 ; i++ ) {
          if ( id(sht3xd_temp).state >= id(temp_level)[i] && id(sht3xd_temp).state <= id(temp_level)[i+1] ) break ;
        }
      currentOutputLevel = i ;
      }
      return currentOutputLevel + 1 ;

number:
  - platform: template
    id: sensitivity_slider
    name: "Sensitivity SoundEsp"
    icon: "mdi:knob"
    update_interval: 5s
    initial_value: "36.5"
    step: 0.1
    min_value: 20
    max_value: 40
    mode: slider
    set_action:
      then:
         lambda:  id(esphome_sensitivity) = x;
